version: "3"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    environment:
      - PGPORT=${POSTGRES_PORT}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    environment:
      - POSTGRES_HOST=database
    ports:
      - "8080:8080"
volumes:
  data:
